name: Build plugins

on:
  push:
    branches: [$default-branch]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [$default-branch]
    paths-ignore:
      - "**.md"

env:
  BUILD_TYPE: release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            OUTPUT_DIR: C:/RoboDK/bin/plugins
            QT_VERSION: "5.15.2"

          - os: ubuntu-latest
            OUTPUT_DIR: ~/RoboDK/bin/plugins
            QT_VERSION: "5.15.2"

          - os: macos-latest
            OUTPUT_DIR: ~/RoboDK-Dev/Deploy/RoboDK.app/Contents/MacOS/plugins
            QT_VERSION: "5.15.2"

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ matrix.QT_VERSION }}

      - name: Configure and build Plug-In-Interface on Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          cd ${{ github.workspace }}
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake CONFIG+=${{ env.BUILD_TYPE }}
          nmake
        shell: cmd

      - name: Configure and build Plug-In-Interface on Unix
        if: (!startsWith(matrix.os, 'windows'))
        run: |
          cd ${{ github.workspace }}
          qmake CONFIG+=${{ env.BUILD_TYPE }}
          make
        shell: bash

      - name: Upload artefacts
        uses: actions/upload-artifact@v2
        with:
          name: Plug-In-Interface-${{ matrix.os }}-${{ env.BUILD_TYPE }}
          path: ${{ matrix.OUTPUT_DIR }}
